/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RetirementRouteImport } from './routes/retirement'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NpsRouteImport } from './routes/nps'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as McxRouteImport } from './routes/mcx'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForexRouteImport } from './routes/forex'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as BrokerConnectRouteImport } from './routes/broker-connect'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsRoute = NpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const McxRoute = McxRouteImport.update({
  id: '/mcx',
  path: '/mcx',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexRoute = ForexRouteImport.update({
  id: '/forex',
  path: '/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerConnectRoute = BrokerConnectRouteImport.update({
  id: '/broker-connect',
  path: '/broker-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/alerts': typeof AlertsRoute
  '/broker-connect': typeof BrokerConnectRoute
  '/budget': typeof BudgetRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forex': typeof ForexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/mcx': typeof McxRoute
  '/mfa': typeof MfaRoute
  '/news': typeof NewsRoute
  '/nps': typeof NpsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/retirement': typeof RetirementRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tax': typeof TaxRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/alerts': typeof AlertsRoute
  '/broker-connect': typeof BrokerConnectRoute
  '/budget': typeof BudgetRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forex': typeof ForexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/mcx': typeof McxRoute
  '/mfa': typeof MfaRoute
  '/news': typeof NewsRoute
  '/nps': typeof NpsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/retirement': typeof RetirementRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tax': typeof TaxRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/alerts': typeof AlertsRoute
  '/broker-connect': typeof BrokerConnectRoute
  '/budget': typeof BudgetRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forex': typeof ForexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/mcx': typeof McxRoute
  '/mfa': typeof MfaRoute
  '/news': typeof NewsRoute
  '/nps': typeof NpsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/retirement': typeof RetirementRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tax': typeof TaxRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-advisor'
    | '/alerts'
    | '/broker-connect'
    | '/budget'
    | '/dashboard'
    | '/documents'
    | '/forex'
    | '/forgot-password'
    | '/goals'
    | '/login'
    | '/market'
    | '/mcx'
    | '/mfa'
    | '/news'
    | '/nps'
    | '/onboarding'
    | '/otp'
    | '/portfolio'
    | '/reports'
    | '/retirement'
    | '/settings'
    | '/signup'
    | '/tax'
    | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-advisor'
    | '/alerts'
    | '/broker-connect'
    | '/budget'
    | '/dashboard'
    | '/documents'
    | '/forex'
    | '/forgot-password'
    | '/goals'
    | '/login'
    | '/market'
    | '/mcx'
    | '/mfa'
    | '/news'
    | '/nps'
    | '/onboarding'
    | '/otp'
    | '/portfolio'
    | '/reports'
    | '/retirement'
    | '/settings'
    | '/signup'
    | '/tax'
    | '/watchlists'
  id:
    | '__root__'
    | '/'
    | '/ai-advisor'
    | '/alerts'
    | '/broker-connect'
    | '/budget'
    | '/dashboard'
    | '/documents'
    | '/forex'
    | '/forgot-password'
    | '/goals'
    | '/login'
    | '/market'
    | '/mcx'
    | '/mfa'
    | '/news'
    | '/nps'
    | '/onboarding'
    | '/otp'
    | '/portfolio'
    | '/reports'
    | '/retirement'
    | '/settings'
    | '/signup'
    | '/tax'
    | '/watchlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  AlertsRoute: typeof AlertsRoute
  BrokerConnectRoute: typeof BrokerConnectRoute
  BudgetRoute: typeof BudgetRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ForexRoute: typeof ForexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoalsRoute: typeof GoalsRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  McxRoute: typeof McxRoute
  MfaRoute: typeof MfaRoute
  NewsRoute: typeof NewsRoute
  NpsRoute: typeof NpsRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  RetirementRoute: typeof RetirementRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TaxRoute: typeof TaxRoute
  WatchlistsRoute: typeof WatchlistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps': {
      id: '/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof NpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcx': {
      id: '/mcx'
      path: '/mcx'
      fullPath: '/mcx'
      preLoaderRoute: typeof McxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex': {
      id: '/forex'
      path: '/forex'
      fullPath: '/forex'
      preLoaderRoute: typeof ForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker-connect': {
      id: '/broker-connect'
      path: '/broker-connect'
      fullPath: '/broker-connect'
      preLoaderRoute: typeof BrokerConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  AlertsRoute: AlertsRoute,
  BrokerConnectRoute: BrokerConnectRoute,
  BudgetRoute: BudgetRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ForexRoute: ForexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoalsRoute: GoalsRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  McxRoute: McxRoute,
  MfaRoute: MfaRoute,
  NewsRoute: NewsRoute,
  NpsRoute: NpsRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  PortfolioRoute: PortfolioRoute,
  ReportsRoute: ReportsRoute,
  RetirementRoute: RetirementRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TaxRoute: TaxRoute,
  WatchlistsRoute: WatchlistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
